name: macOS Debug Session
on: workflow_dispatch

jobs:
  debug:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true